[[cells]]
name = "dao-action-verifier"
enable_type_id = true
location = { file = "build/release/dao-action-verifier" }

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0xe463d7c4cb28457b3a2f735d1d92a971b0f5a751"
hash_type = "type"
