name: pnpm

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize]

jobs:
  pnpm:
    name: pnpm
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["18", "lts/*", "latest"]
        run:
          - pnpm build
          - pnpm lint
          - pnpm test

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.12

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Command
        run: ${{ matrix.run }}
